AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 2.7

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 30

Naming/MethodParameterName:
  MinNameLength: 1

Metrics/BlockLength:
  Exclude:
    - 'spec/*.rb'
