name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7.x', '3.0.x', '3.1.x', '3.2.x']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: |
          gem --version
          gem install bundler
          bundle --version
          bundle install
      - name: Run Rubocop
        run: |
          bundle exec rake rubocop
      - name: Run Sorbet type checker
        run: |
          bundle exec rake sorbet
